import { NextRequest, NextResponse } from "next/server"
import { cookies } from 'next/headers'
import { decode } from 'next-auth/jwt';
import { getUserIdFromEmail } from "@/app/api/db/Users";
import { fetchArtPromptById, fetchArtContentForPrompt, getArtStyleById, getImageOrientationById } from "@/app/api/db/Art";
import { generateSignedUrlFile } from "@/app/api/utils/gcp"
import { validUUIDv7 } from "@/app/utils/DataValidation"

export async function GET(request: NextRequest, { params }: { params: { prompt_id: string } }) {
    try {

        const promptId = params.prompt_id;

        // Return bad request if prompt id passed in get url is not of a valid UUID type
        if (!validUUIDv7(promptId)) {
            return NextResponse.json({
                "response": {
                    "prompt": null,
                    "content": null
                }
            }, {
                status: 400
            });
        }

        // Check cookies to see if next-auth session token exists
        const cookieStore = cookies()
        const nextAuthSessionCookie: any = cookieStore.get('next-auth.session-token');

        // Get user credentials from next-auth session token if it exsists
        let userData: any = null;
        let userId: string = "";
        if (nextAuthSessionCookie !== undefined && nextAuthSessionCookie && "value" in nextAuthSessionCookie) {
            userData = await decode({
                token: nextAuthSessionCookie.value,
                secret: process.env.NEXTAUTH_SECRET!,
            });

            // Get user Id for email decoded in next-auth sessiont token
            const userIdFromEmail = await getUserIdFromEmail(userData.email);
            if ("response" in userIdFromEmail) {
                userId = userIdFromEmail.response[0].id

                // Fetch user literature prompts
                const fetchedArtPrompts = await fetchArtPromptById(promptId);

                if ("response" in fetchedArtPrompts) {
                    let artPromptsAndContent: any = {
                        "prompt": null,
                        "content": null
                    };

                    if (fetchedArtPrompts.response.length > 0) {
                        const prompt: any = fetchedArtPrompts.response[0];

                        // Return forbidden response in the case where the content exists,
                        // but does not belong to the current user
                        if (prompt.user_id !== userId) {
                            return NextResponse.json({
                                "error": "This content was not generated by you."
                            }, {
                                status: 403
                            });
                        }

                        // Fetch user content for art prompt 
                        const fetchedArtContentForPrompt = await fetchArtContentForPrompt(prompt.id);

                        // Get art prompt content type lookup data
                        const artStyleRes: any = await getArtStyleById(prompt.art_style);
                        let finalArtStyle = prompt.art_style;
                        if ("response" in artStyleRes) {
                            finalArtStyle = artStyleRes.response[0];
                        }

                        // Get art prompt image orientation type lookup data
                        const imageOrientationRes: any = await getImageOrientationById(prompt.orientation);
                        let finalImageOrientation = prompt.orientation;
                        if ("response" in artStyleRes) {
                            finalImageOrientation = imageOrientationRes.response[0];
                        }

                        // Get authenticated url for each generated image
                        let finalContent = null;
                        if ("response" in fetchedArtContentForPrompt) {
                            finalContent = await Promise.all(fetchedArtContentForPrompt.response.map(async (content: any, index: number) => {
                                let authenticatedImageUrl: any = content.image_path;
                                const generatedSignedUrl = await generateSignedUrlFile(process.env.GCP_CONTENT_RESULTS_BUCKET!, content.image_path)
                                authenticatedImageUrl = "url" in generatedSignedUrl ? generatedSignedUrl.url : "";
                                return {
                                    ...content,
                                    "image_path": authenticatedImageUrl
                                }
                            }));
                        }

                        artPromptsAndContent = {
                            "prompt": {
                                ...prompt,
                                "art_style": finalArtStyle,
                                "orientation": finalImageOrientation
                            },
                            "content": prompt.success === 1 ? finalContent : null
                        }
                    }

                    return NextResponse.json({
                        "response": artPromptsAndContent
                    }, {
                        status: 200
                    });
                } else {
                    return NextResponse.json({
                        "response": fetchedArtPrompts.error
                    }, {
                        status: 400
                    });
                }
            }
        } else {
            userData = null;
            return NextResponse.json({
                "error": "Unauthenticated user."
            }, {
                status: 403
            });
        }
    } catch (error: any) {
        console.log(`Error fetching literature content history: ${error.message}.`);
        return NextResponse.json({
            "error": error.message
        }, {
            status: 500
        });
    }
}